apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared   # <--- le nom UNIQUE

  steps:
    - name: clone
      image: alpine/git
      script: |
        echo "[CLONE] Cleaning..."
        rm -rf /workspace/shared/repo

        echo "[CLONE] Cloning..."
        git clone $(params.url) /workspace/shared/repo

        cd /workspace/shared/repo
        git checkout $(params.revision)

        echo "[CLONE] Done. Listing:"
        ls -R /workspace/shared/repo
