apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "master"
  workspaces:
    - name: output
  steps:
    - name: clean
      image: alpine
      workingDir: /workspace/output
      script: |
        echo "üßπ Cleaning previous repo directory"
        rm -rf repo
        mkdir -p repo

    - name: clone
      image: alpine/git
      workingDir: /workspace/output
      script: |
        echo "‚¨áÔ∏è Cloning repository"
        git clone $(params.url) repo
        cd repo
        git checkout $(params.revision)

    - name: list
      image: alpine
      workingDir: /workspace/output/repo
      script: |
        echo "üìÅ Repository contents :"
        ls -R .
