apiVersion: v1
kind: Service
metadata:
  name: service-notification
spec:
  selector:
    app: service-notification
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
