apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: run-config-server
  namespace: ci-pipeline
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-microservice
  params:
    - name: url
      value: "https://github.com/Sabrynette/BACKEND-FINAL.git"
    - name: contextDir
      value: "config-server"
    - name: image
      value: "image-registry.openshift-image-registry.svc:5000/ci-pipeline/config-server:latest"
  workspaces:
    - name: shared
      emptyDir: {}
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc
    - name: maven-settings
      configMap:
        name: maven-settings
