apiVersion: v1
kind: Service
metadata:
  name: service-utilisateur
spec:
  selector:
    app: service-utilisateur
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
